### PR TITLE
migrates to GHA

### PR DESCRIPTION
**Pull request by viglucci**
Migrate to GH actions instead of Travis.

### Motivation:

The Travis webhook integration is deprecated + GH actions are currently used in other RSocket projects (such as rsocket-website) for builds and CI tasks.

### Modifications:

Adds GH action + removes Travis config.

### Result:

Tests will run during PR flow.

### CODE REVIEW

**Review by OlegDokuka — APPROVED** [review]
LGTM. We will need to add release pipe, but we can do that separately

**Review by SerCeMan — APPROVED** [review]
LGTM

**Comment by viglucci** [comment]
@OlegDokuka I think we may need to disable the Travis CI check in some way before we can merge this as the PR seems to still gated on whether or not Travis CI completes or not. I don't think I the necessary permissions to make that settings change.

**Comment by OlegDokuka** [comment]
@viglucci I removed Travis so feel free to merge that PR

**Comment by viglucci** [comment]
@OlegDokuka unfortunately I'm still not able to merge this PR as the Travis CI check is still pending/enable for the master branch, or so claims GitHub. I tried creating a new PR and I can't merge that one either. See: https://github.com/rsocket/rsocket-js/pull/146

Additionally, I wasn't able to merge manually as `master` is a protected branch.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
```

**Comment by viglucci** [comment]
Re-opening with the above comment.

**Pull request merged**
