### PR TITLE
chore: remove hasBufferModule code

### PR DESCRIPTION
**Pull request by sudongyuer**
remove hasBufferModule code that makes RSocket-js can't work in browser

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by OlegDokuka** [comment]
hey @sudongyuer ! 


Any particular errors that prevent it from working in the browser?

**Comment by sudongyuer** [comment]
> hey @sudongyuer !
> 
> Any particular errors that prevent it from working in the browser?

#195

**Comment by sudongyuer** [comment]
> > hey @sudongyuer !
> > Any particular errors that prevent it from working in the browser?
> 
> #195

I think it's necessary to remove it

**Comment by viglucci** [comment]
Hi @sudongyuer , I suspect the issue you are experiencing may be due to tooling or something specific to your environment. To test, I was able to create a working example using `create-react-app`. Please see my comment on https://github.com/rsocket/rsocket-js/issues/195#issuecomment-986161901.

**Pull request closed without merging**
